#!/usr/bin/env python3
"""Generate a cell file from any URDF, deriving everything from the URDF itself.

This is the embodiment-agnosticism claim put to work rather than asserted.  The
five cells in the test matrix were authored here, so passing on them proves the
code is consistent -- not that it generalises.  This takes a URDF nobody here has
seen, works out the root, the actuated joints, the tool frames, the limits and a
rest posture, and emits a cell the controller can run unchanged.

Nothing about the robot is supplied by hand: tool frames default to the leaf
links (a link that is no joint's parent), the root is the link that is no joint's
child, and the rest posture is the midpoint of each joint's own range, clipped
into the limits it declares.  Collision spheres are OPTIONAL -- without them the
cell still exercises Layers 1 and 2 and the joint-limit half of Layer 3, which is
what a generality check needs; sphere fitting is a separate concern.

Usage:
    python scripts/cell_from_urdf.py /path/to/robot.urdf --name franka \
        --tcp panda_hand -o configs/generality/franka.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from remoroo_lc.urdf import load_urdf  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("urdf", type=Path)
    ap.add_argument("--name", required=True)
    ap.add_argument("--tcp", nargs="*", default=None, help="tool link names; default = leaves")
    ap.add_argument("--joints", nargs="*", default=None, help="actuated joints; default = all movable")
    ap.add_argument("--limits", default="../limits.yaml")
    ap.add_argument("--max-tcps", type=int, default=2, help="cap on auto-detected tool frames")
    ap.add_argument("-o", "--out", type=Path, required=True)
    a = ap.parse_args()

    urdf = load_urdf(a.urdf)
    children = {j.child for j in urdf.joints}
    parents = {j.parent for j in urdf.joints}
    root = next(ln for ln in urdf.links if ln not in children)
    movable = [j for j in urdf.joints if j.moves]

    joints = a.joints if a.joints else [j.name for j in movable]
    locked = [j.name for j in movable if j.name not in joints]

    if a.tcp:
        tcps = list(a.tcp)
    else:
        leaves = [ln for ln in urdf.links if ln not in parents]
        # Prefer the deepest leaves: most joints between them and the root.
        depth = {}
        pmap = {j.child: j.parent for j in urdf.joints}
        for ln in leaves:
            d, cur = 0, ln
            while cur in pmap:
                d += 1
                cur = pmap[cur]
            depth[ln] = d
        tcps = sorted(leaves, key=lambda ln: -depth[ln])[: a.max_tcps]

    # Rest posture: the middle of each joint's declared range.  A joint with no
    # limits (continuous) rests at zero.
    rest = []
    for name in joints:
        j = next(x for x in urdf.joints if x.name == name)
        lo, hi = float(j.lower), float(j.upper)
        rest.append(0.0 if hi <= lo else round((lo + hi) * 0.5, 6))

    lines = [
        f"# {a.name}: generated by scripts/cell_from_urdf.py from",
        f"#   {a.urdf}",
        "#",
        "# Every field below is DERIVED from that URDF -- root link, actuated joints,",
        "# tool frames (deepest leaves), rest posture (mid-range).  Nothing about this",
        "# robot is hand-written here, which is the point: it is a generality check,",
        "# not a tuned configuration.",
        "",
        'lc_spec_version: "1.0"',
        f"name: {a.name}",
        "",
        f"limits: {a.limits}",
        "gains: ../gains.default.yaml",
        "",
        "models:",
        f"  - name: {a.name}",
        f"    urdf: {a.urdf}",
        "    base:",
        "      xyz: [0.0, 0.0, 0.0]",
        "      rpy: [0.0, 0.0, 0.0]",
        "    joints:",
        "      [" + ", ".join(joints) + "]",
    ]
    if locked:
        lines.append("    locked_joints:")
        for name in locked:
            lines.append(f"      {name}: 0.0")
    lines += [
        "    rest: [" + ", ".join(f"{v}" for v in rest) + "]",
        "",
        "tcps:",
    ]
    for t in tcps:
        lines += [
            f"  - name: {t}",
            f"    model: {a.name}",
            f"    frame: {t}",
            "    damping: { w_thresh: 0.001 }",
        ]
    lines += [
        "",
        "environment: []",
        "",
        "collision:",
        "  self_pairs: true",
        "  cross_model: true",
        "  environment: true",
        "",
    ]
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(lines))
    print(
        f"{a.name}: root={root}  joints={len(joints)}  locked={len(locked)}  "
        f"tcps={tcps}  -> {a.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
